name: Compere functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello World', 'ell') }}
          STARTS_WITH_FUNC: ${{ startsWith('Hello World', 'He') }}
          ENDS_WITH_FUNC: ${{ endsWith('Hello World', 'lo') }}
