name: Literals
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep 'LITERAL_'
        env:
          LTERAL_NULL: ${{null}}
          LTERAL_BOOLEAN: ${{true}}
          LTERAL_NUMBER: ${{1234}}
          LTERAL_STRING: ${{'Hello'}}
          LTERAL_OMIT_STRING: World
